export const COLORS = {
  primary: '#FF6B6B',
  primaryDark: '#EE5A6F',
  secondary: '#FF8E53',
  accent: '#FFA94D',
  success: '#51CF66',
  warning: '#FCC419',
  danger: '#FF6B6B',
  fire: '#FF6B35',
  streak: '#FF4757',
  dark: '#2D3436',
  darkGray: '#636E72',
  gray: '#B2BEC3',
  lightGray: '#DFE6E9',
  background: '#F8F9FA',
  white: '#FFFFFF',
  card: '#FFFFFF',
  gradient1: ['#FF6B6B', '#FF8E53'],
  gradient2: ['#FFA94D', '#FF6B35'],
  gradient3: ['#51CF66', '#38B2AC'],
};

export const LIGHT_COLORS = {
  primary: '#FF6B6B',
  primaryDark: '#EE5A6F',
  secondary: '#FF8E53',
  accent: '#FFA94D',
  success: '#51CF66',
  warning: '#FCC419',
  danger: '#FF6B6B',
  fire: '#FF6B35',
  streak: '#FF4757',
  dark: '#2D3436',
  darkGray: '#636E72',
  gray: '#B2BEC3',
  lightGray: '#DFE6E9',
  background: '#F8F9FA',
  white: '#FFFFFF',
  card: '#FFFFFF',
  gradient1: ['#FF6B6B', '#FF8E53'],
  gradient2: ['#FFA94D', '#FF6B35'],
  gradient3: ['#51CF66', '#38B2AC'],
};

export const DARK_COLORS = {
  primary: '#FF6B6B',
  primaryDark: '#EE5A6F',
  secondary: '#FF8E53',
  accent: '#FFA94D',
  success: '#51CF66',
  warning: '#FCC419',
  danger: '#FF6B6B',
  fire: '#FF6B35',
  streak: '#FF4757',
  dark: '#FFFFFF',
  darkGray: '#E0E0E0',
  gray: '#A0A0A0',
  lightGray: '#4A4A4A',
  background: '#121212',
  white: '#1E1E1E',
  card: '#2A2A2A',
  gradient1: ['#FF6B6B', '#FF8E53'],
  gradient2: ['#FFA94D', '#FF6B35'],
  gradient3: ['#51CF66', '#38B2AC'],
};

export const SIZES = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const FONTS = {
  h1: { fontSize: 32, fontWeight: 'bold' },
  h2: { fontSize: 24, fontWeight: 'bold' },
  h3: { fontSize: 20, fontWeight: '600' },
  h4: { fontSize: 18, fontWeight: '600' },
  body: { fontSize: 16, fontWeight: '400' },
  small: { fontSize: 14, fontWeight: '400' },
  tiny: { fontSize: 12, fontWeight: '400' },
};

export const DAYS = [
  { id: 0, short: 'Paz', full: 'Pazar' },
  { id: 1, short: 'Pzt', full: 'Pazartesi' },
  { id: 2, short: 'Sal', full: 'Salı' },
  { id: 3, short: 'Car', full: 'Carsamba' },
  { id: 4, short: 'Per', full: 'Persembe' },
  { id: 5, short: 'Cum', full: 'Cuma' },
  { id: 6, short: 'Cmt', full: 'Cumartesi' },
];

export const LEVEL_RANKS = [
  { min: 1, max: 10, title: 'Acemi', color: '#95E1D3' },
  { min: 11, max: 25, title: 'Gelisen', color: '#38ADA9' },
  { min: 26, max: 50, title: 'Deneyimli', color: '#F38181' },
  { min: 51, max: 75, title: 'Usta', color: '#AA96DA' },
  { min: 76, max: 100, title: 'Profesyonel', color: '#FCBAD3' },
  { min: 101, max: 150, title: 'Elit', color: '#6C5CE7' },
  { min: 151, max: 999, title: 'Efsane', color: '#FDCB6E' },
];

export const MOTIVATIONAL_QUOTES = [
  'Basari, kucuk cabalarin tekraridir!',
  'Bugün yaptigin, yarinin basarisidir!',
  'Disiplin, özgürlügün köprüsüdür!',
  'Her gün biraz daha iyi!',
  'Aliskanliiklarin gelecegins belirler!',
  'Kucük adimlar, büyük degisimler!',
  'Tutarlilik basarinin anahtaridir!',
  'Bugün kendine yatirim yap!',
];

export const TASK_CATEGORIES = [
  {
    id: 'health',
    name: 'Saglik',
    emoji: '💪',
    iconName: 'fitness',
    color: '#51CF66',
    tasks: [
      { title: '30 dakika yürüyüs yap', points: 20 },
      { title: '2 litre su ic', points: 10 },
      { title: '15 dakika yoga yap', points: 20 },
      { title: '8 saat uyu', points: 10 },
      { title: '1 saat spor yap', points: 30 },
      { title: 'Saglikli kahvalti yap', points: 10 },
    ],
  },
  {
    id: 'productivity',
    name: 'Verimlilik',
    emoji: '🎯',
    iconName: 'rocket',
    color: '#FF8E53',
    tasks: [
      { title: 'Günlük planlama yap', points: 10 },
      { title: '2 saat odakli calisma', points: 30 },
      { title: 'Masani topla', points: 10 },
      { title: 'To-do listeni güncelle', points: 10 },
      { title: 'Pomodoro teknigi uygula', points: 20 },
      { title: 'E-postalari yanitla', points: 10 },
    ],
  },
  {
    id: 'learning',
    name: 'Egitim',
    emoji: '📚',
    iconName: 'book',
    color: '#6C5CE7',
    tasks: [
      { title: '30 dakika kitap oku', points: 20 },
      { title: 'Yeni bir sey ögre', points: 30 },
      { title: 'Online kurs izle', points: 20 },
      { title: '10 sayfa kitap oku', points: 10 },
      { title: 'Yabanci dil calis', points: 20 },
      { title: 'Podcast dinle', points: 10 },
    ],
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    emoji: '🧘',
    iconName: 'leaf',
    color: '#A29BFE',
    tasks: [
      { title: '10 dakika meditasyon', points: 20 },
      { title: 'Günlük tut', points: 10 },
      { title: 'Sükür pratigi yap', points: 10 },
      { title: 'Dogada zaman gecir', points: 20 },
      { title: 'Derin nefes egzersizi', points: 10 },
    ],
  },
  {
    id: 'social',
    name: 'Sosyal',
    emoji: '👥',
    iconName: 'people',
    color: '#FD79A8',
    tasks: [
      { title: 'Arkadasinla görüs', points: 20 },
      { title: 'Aileyle kaliteli zaman', points: 20 },
      { title: 'Birini ara veya mesaj at', points: 10 },
      { title: 'Sosyal aktiviteye katil', points: 30 },
    ],
  },
  {
    id: 'creative',
    name: 'Yaraticilik',
    emoji: '🎨',
    iconName: 'color-palette',
    color: '#FDCB6E',
    tasks: [
      { title: 'Bir seyler ciz', points: 20 },
      { title: 'Müzik dinle veya cal', points: 10 },
      { title: 'Fotograf cek', points: 10 },
      { title: 'Yaratici yazi yaz', points: 20 },
      { title: 'El isi yap', points: 20 },
    ],
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'first_task',
    title: 'Ilk Adim',
    emoji: '🎯',
    description: 'Ilk görevini tamamla',
    requirement: 'totalTasks',
    value: 1,
    hidden: false,
  },
  {
    id: 'week_warrior',
    title: 'Haftalik Savascı',
    emoji: '🔥',
    description: '7 gün üst üste görev tamamla',
    requirement: 'streak',
    value: 7,
    hidden: false,
  },
  {
    id: 'month_master',
    title: 'Aylik Kral',
    emoji: '👑',
    description: '30 gün üst üste görev tamamla',
    requirement: 'streak',
    value: 30,
    hidden: false,
  },
  {
    id: 'super_active',
    title: 'Süper Aktif',
    emoji: '⚡',
    description: 'Toplam 50 görev tamamla',
    requirement: 'totalTasks',
    value: 50,
    hidden: false,
  },
  {
    id: 'centurion',
    title: 'Yüzlük',
    emoji: '💯',
    description: 'Toplam 100 görev tamamla',
    requirement: 'totalTasks',
    value: 100,
    hidden: false,
  },
  {
    id: 'level_master',
    title: 'Seviye Ustasi',
    emoji: '🌟',
    description: 'Seviye 10a ulaş',
    requirement: 'level',
    value: 10,
    hidden: false,
  },
  {
    id: 'point_collector',
    title: 'Puan Avcisi',
    emoji: '🏆',
    description: '1000 puan topla',
    requirement: 'points',
    value: 1000,
    hidden: false,
  },
  {
    id: 'perfect_day',
    title: 'Mükemmel Gün',
    emoji: '✨',
    description: 'Bir günün tüm görevlerini tamamla',
    requirement: 'perfectDay',
    value: 1,
    hidden: false,
  },
  {
    id: 'night_owl',
    title: 'Gece Kusu',
    emoji: '🦉',
    description: 'Gece 22 den sonra 5 görev tamamla',
    requirement: 'nightOwl',
    value: 5,
    hidden: true,
  },
  {
    id: 'perfectionist',
    title: 'Mükemmeliyetci',
    emoji: '💎',
    description: '5 gün üst üste tüm görevleri tamamla',
    requirement: 'perfectStreak',
    value: 5,
    hidden: true,
  },
];

export const SHOP_ITEMS = [
  {
    id: 'streak_freeze',
    name: 'Seri Dondurucu',
    emoji: '❄️',
    description: '1 gün görev yapmasan bile serini korur',
    price: 100,
    type: 'consumable',
    icon: 'snow',
    gradient: ['#74b9ff', '#0984e3'],
  },
  {
    id: 'double_points',
    name: 'Cift Puan',
    emoji: '⚡',
    description: '1 gün boyunca puanlarin 2 katina cikar',
    price: 150,
    type: 'consumable',
    icon: 'flash',
    gradient: ['#fdcb6e', '#e17055'],
  },
  {
    id: 'streak_freeze_3',
    name: '3x Seri Dondurucu',
    emoji: '🧊',
    description: '3 adet seri dondurucu paketi',
    price: 250,
    type: 'consumable',
    icon: 'snow',
    gradient: ['#55efc4', '#00b894'],
    amount: 3,
  },
  {
    id: 'theme_default',
    name: 'Varsayilan Tema',
    emoji: '🔥',
    description: 'Kirmizi turuncu klasik tema',
    price: 0,
    type: 'theme',
    icon: 'flame',
    gradient: ['#FF6B6B', '#FF8E53'],
    primaryColor: '#FF6B6B',
    free: true,
  },
  {
    id: 'theme_ocean',
    name: 'Okyanus Temasi',
    emoji: '🌊',
    description: 'Derin mavi sakinligi',
    price: 500,
    type: 'theme',
    icon: 'water',
    gradient: ['#667eea', '#764ba2'],
    primaryColor: '#667eea',
  },
  {
    id: 'theme_sunset',
    name: 'Gün Batimi',
    emoji: '🌅',
    description: 'Turuncu pembe sicakligi',
    price: 500,
    type: 'theme',
    icon: 'sunny',
    gradient: ['#f093fb', '#f5576c'],
    primaryColor: '#f5576c',
  },
  {
    id: 'theme_forest',
    name: 'Orman Temasi',
    emoji: '🌿',
    description: 'Doganin yesil huzuru',
    price: 500,
    type: 'theme',
    icon: 'leaf',
    gradient: ['#11998e', '#38ef7d'],
    primaryColor: '#11998e',
  },
  {
    id: 'theme_galaxy',
    name: 'Galaksi Temasi',
    emoji: '🌌',
    description: 'Uzayin koyu sikligi',
    price: 750,
    type: 'theme',
    icon: 'planet',
    gradient: ['#2C3E50', '#4CA1AF'],
    primaryColor: '#4CA1AF',
  },
  {
    id: 'theme_gold',
    name: 'Altin Tema',
    emoji: '👑',
    description: 'Prestijli altin görünümü',
    price: 1000,
    type: 'theme',
    icon: 'trophy',
    gradient: ['#F7971E', '#FFD200'],
    primaryColor: '#F7971E',
  },
];